name: Test database permissions
on:
  push:
  pull_request:
jobs:
  rls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v3
        with:
          version: 2.118.0
      - run: supabase db start
      - run: supabase test db
